### ISSUE TITLE
Request for information on serial and parallel R jobs

### ISSUE THREAD

**Issue by pablobernabeu** [UNINETTSigma2/documentation#13]
Dear All,

I am a user of Saga and would like to ask you if you could please point me to some information regarding how to run R jobs in Saga. I have found some [information](https://documentation.sigma2.no/software/application_guides/r.html?highlight=modules%20r%20jobs) ([source code](https://github.com/UNINETTSigma2/documentation/blob/master/software/application_guides/r.md)) but no examples of how to run R jobs from R scripts, rather than from bash scripts.

In a previous HPC I used, I would have an R script (`.R` or `.Rmd`) along with a `.com` script. In the `.com` script, there was a call to the R module and a call to the R script. An example of a .com script for a serial job is below:

```
#$ -S /bin/bash

#$ -q serial
#$ -N name_of_my_job

source /etc/profile

module add R/4.0.2

R CMD BATCH --no-save name_of_my_job.R
```

Last, the `.com` script (for instance, named `name_of_my_job.com`) would be run in the HPC terminal with the following command: 

`qsub -m e -M myemailaddress@gmail.com -l h_vmem=25G name_of_my_job.com`

The system for parallel jobs was essentially the same, with subtle but important differences.

Thank you very much for your attention

**Comment by bast** [comment]
Dear Pablo, I will either find one or write one. I will come back with something very soon.

**Comment by bast** [comment]
Do you have a simple example for a parallel R script so that I can test it?

**Comment by pablobernabeu** [comment]
Thank you, Radovan. Please find below a simple example (basic math operations in a loop) from https://www.hpc.ntnu.no/parallel-r-for-hpc-system. I've edited it to add `istart` and `iend`.

```
library(doParallel)
registerDoParallel(cores=20)
n<-20000
m<-100000

istart<-1
iend<-10000
 
ls<-0.0
gsum<-foreach(i=istart:iend,.combine='+') %dopar% {
   for(j in 1:m) {
       ls<-ls+sqrt(i+j)+cos(i+j)+sin(i+j)
   }
   ls
}
sprintf("Sum %f",gsum)
```

**Comment by bast** [comment]
Awesome. I am working on it and will hopefully have something later today.

**Comment by pablobernabeu** [comment]
Thank you very much! 

I just edited the code to add `istart` and `iend`.

**Comment by bast** [comment]
We have an example soon. I am only waiting for my change to get merged and then I will notify you.

**Comment by pablobernabeu** [comment]
That's great! Thank you very much

**Comment by bast** [comment]
Here is an example:
- https://documentation.sigma2.no/getting_started/R.html
- https://documentation.sigma2.no/software/userinstallsw/R.html#installing-r-libraries

**Comment by pablobernabeu** [comment]
Brilliant. Thank you very much
