### ISSUE TITLE
update python versions

### ISSUE THREAD

**Issue by franzihe** [UNINETTSigma2/documentation#8]
File:  documentation/software/installed_software/fram_modules.md 

## Python
----------------------------------------------------------------
Installed versions:
should be updated with `Python/3.8.6-GCCcore-10.2.0` or the newest version available.

**Comment by bast** [comment]
Thanks for reporting!

**Comment by bast** [comment]
We decided to remove this page altogether to minimize confusion.

For motivation why, please see https://github.com/UNINETTSigma2/documentation/commit/f115d5e3bf71af55d9dfda5d651b610481801bc7.
